stages:
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn clean package -B
  artifacts:
    paths:
      - target/*.war

deploy:
  stage: deploy
  image: tomcat:9-jdk8
  script:
    - curl -T target/*.war "localhost:8080/manager/text/deploy?path=/myapp&update=true"
  environment:
    name: dev
    url: localhost:8080/myapp
